### ISSUE TITLE
Implement basic navigation 

### ISSUE THREAD

**Issue by anirudhk-tech** [acm-uic/SIG-Mobile-Development#3]
Assigned to: Ryan

I want you to get familiar with GetX and it's navigation. It's really good with state management as well. I think you'll pick it up very really quick since you worked with Flutter state before. 

By the time you're done, you should be able to:
1. Switch between screens through the bottom tab navigator
2. Learn how GetX navigation works

**Comment by schmerble** [comment]
Done
